<?php
// app/Helpers/Contoh.php

namespace App\Helpers;

use App\Models\Transaksi;
use App\Models\JenisPembayaran;
use App\Models\Tikets;
use Illuminate\Support\Facades\Http;
use GuzzleHttp\Client;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use SVG\SVG;
use Illuminate\Support\Facades\Storage;
use Milon\Barcode\DNS1D;


class SadewaPDF
{
    public static function Invoice($order_id)
    {
        //transaksi
        $transaksi = Transaksi::where('order_id', $order_id)->where('status', '1')->first();
        if ($transaksi == null) {
            new \Exception('transaksi tidak ditemukan');
        }
        //keranjang
        $keranjangs = $transaksi->keranjang()->where('status_id', 3)->get();

        //qr code
        $qrCode = QrCode::format('svg')->size(100)->generate(config('app.url') . "/tiket/detail/" . $transaksi->order_id);
        $image = SVG::fromString($qrCode);
        $image = $image->toRasterImage(500, 500);
        $image = imagecrop($image, ['x' => 0, 'y' => 0, 'width' => 146, 'height' => 146]);
        imagepng($image, 'assets/qr/image.png');

        //midtrans
        $client = new Client([
            'verify' => public_path('images/cacert.pem'), // Specify the path to the downloaded cacert.pem file
        ]);
        $response = $client->request('GET', 'https://api.sandbox.midtrans.com/v2/' . $transaksi->order_id . '/status', [
            'auth' => [config('midtrans.server_key'), '']
        ]);
        $statusCode = $response->getStatusCode();
        if ($statusCode == 200) {
            $body = $response->getBody();
            $midtrans = json_decode($body, true);
            if (!isset($midtrans['order_id'])) {
                return dd($midtrans);
            }
        } else {
            throw new \Exception('gagal meraih server');
        }

        //pdf
        $pdf = new customPDF('P', 'mm', 'A4');
        $pdf->setLogo('assets/img/Logo sadewa.png');
        $pdf->setJudul("Invoice");

        //info
        $pdf->SetTitle('Surat transaksi ' . $transaksi->order_id);
        $pdf->SetAuthor('SADEWA - CV Oase Smart Solusindo');
        $pdf->SetSubject('Tiket Transaksi');
        $pdf->SetCreator('generated by FPDF');
        $pdf->SetMargins(5, 5, 5, 5);
        $pdf->AddPage();
        $pdf->SetFont('Arial', '', 8);

        //atas
        $pdf->Image(public_path('assets/qr/image.png'), 50, 26, 20);
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->Cell(110, 48, $transaksi->order_id, 0, 0, 'C');
        $pdf->SetFont('Arial', '', 8);
        $pdf->Cell(20);
        $pdf->Cell(25, 5, 'Nama Pemesan', 0, 0, 'L');
        $pdf->Cell(45, 5, ': ' . $transaksi->nama_pemesan, 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(130);
        $pdf->Cell(25, 5, 'No. telp', 0, 0, 'L');
        $pdf->Cell(45, 5, ': ' . $transaksi->no_telp_pemesan, 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(130);
        $pdf->Cell(25, 5, 'E-mail', 0, 0, 'L');
        $pdf->Cell(45, 5, ': ' . $transaksi->email_pemesan, 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(130);
        $pdf->Cell(25, 5, 'No. pemesanan', 0, 0, 'L');
        $pdf->Cell(45, 5, ': ' . $transaksi->order_id, 0, 0, 'L');
        $pdf->Ln(15);

        $pdf->SetDrawColor(149, 161, 173);
        $pdf->SetFont('Arial', 'B', 8);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->Ln(5);

        //tengah
        //header
        $pdf->Cell(15, 10, 'index', 'TLB', 0, 'C');
        $pdf->Cell(25, 10, 'jenis', 'TBL', 0, 'C');
        $pdf->Cell(85, 5, 'keterangan', 'TBLR', 0, 'C');
        $pdf->Cell(30, 10, 'harga', 'TB', 0, 'C');
        $pdf->Cell(15, 10, 'jumlah', 'TLB', 0, 'C');
        $pdf->Cell(0, 10, 'subtotal', 'TLRB', 0, 'C');
        //subheader
        $pdf->Ln(5);
        $pdf->Cell(40);
        $pdf->Cell(60, 5, 'nama', 'BLR', 0, 'C');
        $pdf->Cell(25, 5, 'harga', 'BLR', 0, 'C');

        //font untuk isi
        $pdf->SetFont('Arial', '', 8);
        $iterasi = 0;
        //isi
        foreach ($keranjangs as $keranjang) {
            $iterasi++;
            $tinggi = $keranjang->paketWahana()->wherePivot('index', 1)->count() * 5 + 5;
            $pdf->Ln(5);
            $pdf->Cell(15, $tinggi, $iterasi, 'BL', 0, 'C');
            $pdf->Cell(25, $tinggi, $keranjang->tipe, 'BLR', 0, 'C');
            if ($keranjang->tipe == "paket") {
                $first_item = $keranjang->paketDestinasi()->wherePivot('index', 1)->first();
                $pdf->Cell(60, 5, $first_item->nama_paket, 'BL', 0, 'L');
                $pdf->Cell(25, 5, $first_item->harga_paket, 'BL', 0, 'R');
            } else {
                $first_item = $keranjang->destinasi()->wherePivot('index', 1)->first();
                $pdf->Cell(60, 5, 'Tiket ' . $first_item->nama_destinasi, 'BL', 0, 'L');
                $pdf->Cell(25, 5, $first_item->htm_destinasi, 'BL', 0, 'R');
            }
            $pdf->Cell(30, $tinggi, $keranjang->total_pembayaran, 'BL', 0, 'C');
            $pdf->Cell(15, $tinggi, $keranjang->jumlah, 'BL', 0, 'C');
            $pdf->Cell(0, $tinggi, $keranjang->total_pembayaran * $keranjang->jumlah, 'BLR', 0, 'C');
            foreach ($keranjang->paketWahana()->wherePivot('index', 1)->get() as $paket_wahana) {
                $pdf->Ln(5);
                $pdf->Cell(40);
                $pdf->Cell(60, 5, $paket_wahana->nama_paket, 'BLR', 0, 'L');
                $pdf->Cell(25, 5, $paket_wahana->harga_paket, 'BLR', 0, 'R');
            }
        }
        $pdf->Ln(10);
        $pdf->Cell(125);
        $pdf->SetFont('Arial', 'B', 8);
        $pdf->Cell(45, 5, 'Total pembayaran :', 0, 0, 'R');
        $pdf->Cell(0, 5, $transaksi->total_pembayaran, 1, 0, 'C');

        //bawah
        $pdf->Ln(10);
        $pdf->SetFont('Arial', '', 8);
        $pdf->SetFont('Helvetica', 'B', 8);
        $pdf->SetTextColor(12, 62, 114);
        $pdf->Cell(0, 5, 'Detail Lainnya', 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->SetFont('Arial', '', 8);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->Cell(35, 5, 'Order ID', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . $midtrans['order_id'], 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(35, 5, 'Total dibayar', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . $midtrans['gross_amount'], 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(35, 5, 'Mata uang', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . $midtrans['currency'], 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(35, 5, 'Tipe pembayaran', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . JenisPembayaran::where('identifikasi_transaksi', true)->where('kode', $midtrans['payment_type'])->first()->nama, 0, 0, 'L');
        $pdf->Ln(5);
        $pdf->Cell(35, 5, 'Waktu transaksi', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . $midtrans['transaction_time'], 0, 0, 'L');
        $pdf->Ln(5);

        $pdf->Cell(35, 5, 'Status transaksi', 0, 0, 'L');
        //Macam-macam transaction_status :
        // capture          : pembayaran telah berhasil dilakukan dan masuk
        // settlement       : pembayaran sudah berhasil sejak 1x24 jam yang lalu (tingkat lanjut dari capture)
        // pending          : pembayaran belum dibayar
        // deny             : kredensial pembayaran tidak valid
        // cancel           : pembayaran dibatalkan oleh penjual
        // expire           : pembayaran sudah kadaluarsa
        // failure          : pembayaran gagal dilakukan yang tidak terduga
        // refund           : pembayaran dikembalikan penjual
        // partial_refund   : pembayaran dikembalikan sebagian oleh penjual
        // authorize        : transaksi berhasil dan sedang dikonfirmasi penjual
        $status = "tidak diketahui";

        if (in_array($midtrans['transaction_status'], ["capture", "settlement"])) {
            $status = "diterima";
        } else if ($midtrans['transaction_status'] == "pending") {
            $status = "menunggu pembayaran";
        } else if ($midtrans['transaction_status'] == "deny") {
            $status = "pembayaran tidak valid";
        } else if ($midtrans['transaction_status'] == "cancel") {
            $status = "pembayaran dibatalkan admin";
        } else if ($midtrans['transaction_status'] == "expire") {
            $status = "pembayaran kadaluarsa";
        } else if ($midtrans['transaction_status'] == "failure") {
            $status = "pembayaran gagal";
        } else if ($midtrans['transaction_status'] == "refund") {
            $status = "telah dikembalikan";
        } else if ($midtrans['transaction_status'] == "partial_refund") {
            $status = "telah dikembalikan sebagian";
        } else if ($midtrans['transaction_status'] == "authorize") {
            $status = "sedang dikonfirmasi admin";
        }

        $pdf->Cell(0, 5, ': ' . $status, 0, 0, 'L');

        $pdf->Ln(5);
        $fraud = "tidak diketahui";
        if ($midtrans['fraud_status'] == "accept") {
            $fraud = "valid";
        } else if ($midtrans['fraud_status'] == "deny") {
            $fraud = "tidak valid";
        }

        $pdf->Cell(35, 5, 'Kredensial', 0, 0, 'L');
        $pdf->Cell(0, 5, ': ' . $fraud, 0, 0, 'L');

        switch ($midtrans['payment_type']) {
            case "credit_card":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Kartu', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['masked_card'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Tipe', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['card_type'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Bank', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['bank'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Respon', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['channel_response_message'], 0, 0, 'L');
                break;
            case "qris":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Tipe transaksi', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['transaction_type'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Penerbit', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['issuer'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Pengakuisisi', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['acquirer'], 0, 0, 'L');
                break;
            case "akulaku":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                break;
            case "bank_transfer":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                if (isset($midtrans['va_numbers'])) {
                    $pdf->Ln(5);
                    $pdf->SetFont('Arial', 'B', 8);
                    $pdf->Cell(35, 5, 'Nomor va', 0, 0, 'L');
                    $pdf->SetFont('Arial', '', 8);
                    if (count($midtrans['va_numbers']) > 0) {
                        $pdf->Cell(0);
                        foreach ($midtrans['va_numbers'] as $va) {
                            $pdf->Ln(5);
                            $pdf->Cell(35);
                            $pdf->Cell(20, 5, 'No.', 0, 0, 'L');
                            $pdf->Cell(0, 5, ': ' . $va['va_number'], 0, 0, 'L');
                            $pdf->Ln(5);
                            $pdf->Cell(35);
                            $pdf->Cell(20, 5, 'Bank', 0, 0, 'L');
                            $pdf->Cell(0, 5, ': ' . $va['bank'], 0, 0, 'L');
                        }
                    } else {
                        $pdf->Cell(0, 5, ': Tidak tercatat', 0, 0, 'L');
                    }
                } else if (isset($midtrans['permata_va_number'])) {
                    $pdf->Ln(5);
                    $pdf->Cell(35, 5, 'No. VA permata bank', 0, 0, 'L');
                    $pdf->Cell(0, 5, ': ' . $midtrans['permata_va_number'], 0, 0, 'L');
                }
                if (isset($midtrans['payment_amounts'])) {
                    $pdf->Ln(5);
                    $pdf->SetFont('Arial', 'B', 8);
                    $pdf->Cell(35, 5, 'Rincian pembayaran', 0, 0, 'L');
                    $pdf->SetFont('Arial', '', 8);
                    if (count($midtrans['payment_amounts']) > 0) {
                        $pdf->Cell(0);
                        foreach ($midtrans['payment_amounts'] as $payment_amount) {
                            $pdf->Ln(5);
                            $pdf->Cell(35);
                            $pdf->Cell(20, 5, 'Dibayar pada', 0, 0, 'L');
                            $pdf->Cell(0, 5, ': ' . $payment_amount['paid_at'], 0, 0, 'L');
                            $pdf->Ln(5);
                            $pdf->Cell(35);
                            $pdf->Cell(20, 5, 'Jumlah', 0, 0, 'L');
                            $pdf->Cell(0, 5, ': ' . $payment_amount['amount'], 0, 0, 'L');
                        }
                    } else {
                        $pdf->Cell(0, 5, ': Tidak tercatat', 0, 0, 'L');
                    }
                }
                break;
            case "echannel":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Kode bill', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['biller_code'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Bill key', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['bill_key'], 0, 0, 'L');
                break;
            case "cstore":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Toko', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['store'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Kode pembayaran', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['payment_code'], 0, 0, 'L');
                if (isset($midtrans['approval_code'])) {
                    $pdf->Ln(5);
                    $pdf->Cell(35, 5, 'Kode persetujuan', 0, 0, 'L');
                    $pdf->Cell(0, 5, ': ' . $midtrans['approval_code'], 0, 0, 'L');
                }
                break;
            case "danamon_online":
            case "cimb_clicks":
            case "bca_klikpay":
            case "bri_epay":
            case "uob_ezpay":
            case "kredivo":
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Waktu terselesaikan', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['settlement_time'], 0, 0, 'L');
                $pdf->Ln(5);
                $pdf->Cell(35, 5, 'Kode approval', 0, 0, 'L');
                $pdf->Cell(0, 5, ': ' . $midtrans['approval_code'], 0, 0, 'L');
                break;
        }

        return $pdf;
    }

    public static function Tiket($tiket_id)
    {
        $tiket = Tikets::where('id', $tiket_id)->first();
        $keranjang = $tiket->keranjang()->first();
        $transaksi = $keranjang->transaksi()->first();
        $destinasi = $tiket->destinasi()->first();
        $wahanas = $tiket->wahana()->get();
        // return response()->json([
        //      'wahana' => $wahanas,
        // ]);
        $ketentuan_array = [
            "2. Saat ingin masuk ke destinasi/wahana,",
            "tunjukkan tiket ini kepada petugas.",
            "3. Petugas akan memindai tiket ini.",
            "4. Tiket ini hanya berlaku 1x setiap wahana",
            "yang terdaftar di bagian kiri",
        ];

        $barcode = barcode::generate($tiket->kode_tiket);
        $pdf = new customPDF('L', 'mm', 'A5');
        $pdf->setJudul("Tiket - order ID : " . $transaksi->order_id);
        $pdf->setLogo('logo/'.$destinasi->logo);
        $pdf->SetTitle('Tiket ' . $tiket->kode_tiket.' - SADEWA');
        $pdf->SetAuthor('SADEWA - CV Oase Smart Solusindo');
        $pdf->SetSubject('Tiket Transaksi');
        $pdf->SetCreator('generated by FPDF');
        $pdf->SetMargins(5, 5, 5, 5);
        $pdf->AddPage();
        $pdf->SetFont('Arial', '', 8);
        $pdf->Image('data://text/plain;base64,'.$barcode, 25, 30, 0,0,'png');
        $pdf->SetFont('Arial', 'B', 20);
        $pdf->Ln(25);
        $pdf->Cell(0, 10, $tiket->kode_tiket, 0, 1, 'C');
        $pdf->SetFont('Arial', '', 10);
        $pdf->Ln(10);
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->Cell(125, 5, 'Tiket ini bisa dipakai untuk :', 0, 0, 'L');
        $pdf->SetFillColor(149, 161, 173);
        $pdf->SetFont('Arial', 'I', 10);
        $pdf->Cell(0, 5, 'Cara memakai tiket :', 0, 1, 'L', true);
        $pdf->SetFont('Arial', '', 10);
        $pdf->Cell(125, 5, $destinasi->nama_destinasi.' ('.$keranjang->tanggal_kunjungan.')', 0, 0, 'L');
        $pdf->SetFont('Arial', 'I', 10);
        $pdf->Cell(0, 5, '1. Tiket ini dibawa saat berkunjung ke tempat', 0, 1, 'L', true);
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->Cell(125, 5, 'Wahana :', 0, 0, 'L');
        $pdf->SetFont('Arial', 'I', 10);
        $pdf->Cell(0, 5, 'wisata bersangkutan.', 0, 1, 'L', true);
        if ($wahanas->count() <= 7) {
            for($i = 0; $i <= 7; $i++) {
                if (isset($wahanas[$i])) {
                    $pdf->SetFont('Arial', '', 10);
                    $pdf->Cell(125, 5, ($i+1).'.) '.$wahanas[$i]->nama_wahana, 0, 0, 'L');
                } else {
                    $pdf->Cell(125, 5, '', 0, 0, 'L');
                }
                if (isset($ketentuan_array[$i])) {
                    $pdf->SetFont('Arial', 'I', 10);
                    $pdf->Cell(0, 5, $ketentuan_array[$i], 0, 1, 'L', true);
                } else {
                    $pdf->Cell(0, 5, '', 0, 1, 'L', true);
                }
            }
        } else {
            for($i = 0; $i <= $wahanas->count(); $i++) {
                if (isset($wahanas[$i])) {
                    $pdf->SetFont('Arial', '', 10);
                    $pdf->Cell(125, 5, ($i+1).'.) '.$wahanas[$i]->nama_wahana, 0, 0, 'L');
                } else {
                    $pdf->Cell(125, 5, '', 0, 0, 'L');
                }
                if (isset($ketentuan_array[$i])) {
                    $pdf->SetFont('Arial', 'I', 10);
                    $pdf->Cell(0, 5, $ketentuan_array[$i], 0, 1, 'L', true);
                } else {
                    $pdf->Cell(0, 5, '', 0, 1, 'L', true);
                }
            }
        }
        return $pdf;        
    }
}

class barcode
{
    public static function generate($kode_tiket)
    {
        $barcode = new DNS1D();
        return $barcode->getBarcodePNG($kode_tiket, "C128", 3, 70);
    }
}

class customPDF extends \FPDF
{
    public $last_y = 0;
    public $title = "";
    public $logo = "";

    function Header()
    {
        $this->Image(public_path($this->logo), 160, 6, 42);
        $this->SetFont('Helvetica', 'B', 20);
        $this->SetTextColor(12, 62, 114);
        $this->SetDrawColor(222, 226, 240);
        $this->Cell(0, 15, $this->title, 'B', 2, 'L');
        $this->Ln(5);
    }
    function Footer()
    {
        $this->SetY(-10);
        $this->SetFont('Arial', '', 8);
        $this->SetTextColor(113, 116, 119);
        $this->Cell(0, 10, 'Terima kasih telah melakukan pemesanan tiket di SADEWA.', 0, 0, 'L');
        $this->Cell(0, 10, 'Copyright 2023 All rights reserved | kontak : kontak@d3ti.vokasi.uns.ac.id', 0, 0, 'R');
    }

    function customCell($width, $height, $string, $border, $align)
    {
        $current_y = $this->GetY();
        $current_x = $this->GetX();
        $this->MultiCell($width, $height, $string, $border, $align);
        $current_x += $width;

        //set last Y
        $last_y = $this->getLastY();
        $new_last_y = $this->getY();
        $last_y = ($new_last_y > $last_y) ? $new_last_y : $last_y;
        $this->setLastY($last_y);

        //set coor just as usual
        $this->SetXY($current_x, $current_y);
    }

    public function getLastY()
    {
        return $this->last_y;
    }

    public function setLastY($last_y)
    {
        $this->last_y = $last_y;
    }

    public function setJudul($title)
    {
        $this->title = $title;
    }

    public function getJudul()
    {
        return  $this->title;
    }

    public function setLogo($logo)
    {
        $this->logo = $logo;
    }

    public function getLogo()
    {
        return  $this->logo;
    }
}
